version: '3.5'

networks:
  telegramdocker:
    driver: bridge

services:
  telegramdocker:
    container_name: servicebot_container
    image: servicebot_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=88
    ports:
    - "88:88"
    networks:
      - telegramdocker
    restart: unless-stopped